//
//  GardeGuardianKit.h
//  GardenGuardian
//
//  Created by Jake Graham on 3/30/17.
//  Copyright (c) 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface GardenGuardianKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sunTabIconTargets;

// Drawing Methods
+ (void)drawSunWithSunFill: (CGFloat)sunFill;
+ (void)drawSunTabIcon;
+ (void)drawRaindropWithWaterFill: (CGFloat)waterFill;
+ (void)drawMoistureTabIcon;
+ (void)drawTempWithTempFill: (CGFloat)tempFill;
+ (void)drawTempTabIcon;
+ (void)drawPHVial;
+ (void)drawPHTabIcon;

// Generated Images
+ (UIImage*)imageOfSunWithSunFill: (CGFloat)sunFill;
+ (UIImage*)imageOfSunTabIcon;
+ (UIImage*)imageOfRaindropWithWaterFill: (CGFloat)waterFill;
+ (UIImage*)imageOfTempWithTempFill: (CGFloat)tempFill;
+ (UIImage*)imageOfPHVial;

@end
